services:
  community-be:
    image: public.ecr.aws/a3y4e2t5/ktb-community/be-registry:latest
    container_name: community-be
    restart: unless-stopped
    networks:
      - community-network
    ports:
      - "8080:8080"

networks:
  community-network:
    driver: bridge