spring:
  application:
    name: "community"

  messages:
    basename: "ValidationMessages"
    encoding: "UTF-8"

  servlet:
    multipart:
      max-file-size: "5MB"
      max-request-size: "25MB"
      file-size-threshold: "2MB"
      resolve-lazily: true

  mvc:
    servlet:
      path: "/api"