spring:
  config:
    activate:
      on-profile: prod
    import: aws-parameterstore:/ktb-community-backend-ps

  datasource:
    url: jdbc:mysql://${DB_URL}:3306/community?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: never
    timeout: ${SESSION_TIMEOUT}

logging:
  level:
    org.hibernate: INFO
    org.springframework: INFO
    com.zaxxer.hikari: INFO

cors:
  allow-credentials: ${CORS_ALLOW_CREDENTIALS}
  allowed-origins: ${CORS_ALLOWED_ORIGINS}
  allowed-methods: ${CORS_ALLOWED_METHODS}
  allowed-headers: ${CORS_ALLOWED_HEADERS}
  max-age: ${CORS_MAX_AGE}

auth:
  excluded-paths: ${AUTH_EXCLUDED_PATHS}