spring:
  application:
    name: "community"

  messages:
    basename: "ValidationMessages"
    encoding: "UTF-8"

  servlet:
    multipart:
      max-file-size: "5MB"
      max-request-size: "25MB"
      file-size-threshold: "2MB"
      resolve-lazily: true

cors:
  allow-credentials: true
  allowed-origins: "http://localhost:3000"
  allowed-methods: "GET, POST, PUT, DELETE, OPTIONS"
  allowed-headers: "*"
  max-age: 3600

auth:
  excluded-paths: "/auth, /users, /users/check-email, /users/check-nickname, /terms, /privacy, /error, /images/profile-img"